### ISSUE TITLE
Issues with update to Prawn

### ISSUE THREAD

**Issue by instructit** [excid3/receipts#1]
After installing this gem file, when trying to run "rails s", I get this error:

/.rvm/gems/ruby-2.2.0/gems/receipts-0.1.0/lib/receipts/receipt.rb:2:in `<module:Receipts>': uninitialized constant Receipts::Prawn (NameError)
	/.rvm/gems/ruby-2.2.0/gems/receipts-0.1.0/lib/receipts/receipt.rb:1:in `<top (required)>'

Not sure if this is related to the recent update with Prawn?

**Comment by excid3** [comment]
This is definitely broken right now. I forgot to add the require statements for prawn and prawn-table to the receipt.rb file.

Happy to accept a pull request for that if you like! I'm at Railsconf right now and don't quite have the time to fix that right away but I can probably get to it tomorrow or Friday at some point.

**Comment by instructit** [comment]
Wonderful. I wish I knew more about Ruby and Rails to help out and fix. In the meantime I can wait and see the changes in the code. I will also say this was a wonderful learning experience to figure out the error. Thank you.

**Comment by DavidVII** [comment]
Take a look #2, @excid3. That should fix the issue, but it might be a good idea to add some tests to this gem to prevent these sorts of issues in the future.

**Comment by excid3** [comment]
Thanks @DavidVII! 

@instructit This should be fixed now and I released version 0.1.1 of the gem with the fix included so you should be able to use it from Rubygems now.

**Comment by instructit** [comment]
Perfect, thank you!
