### ISSUE TITLE
Prawn::Errors::IncompatibleStringEncoding: Your document includes text that's not compatible with the Windows-1252 character set. If you need full UTF-8 support, use external fonts instead of PDF's built-in fonts.

### ISSUE THREAD

**Issue by pbmarcano** [excid3/receipts#21]
Hey there,

I have a customer that signed up a Twitter app of mine, paid for it with the `pay` gem, and when I try to send them a receipt I get this error.

```Prawn::Errors::IncompatibleStringEncoding: Your document includes text that's not compatible with the Windows-1252 character set. If you need full UTF-8 support, use external fonts instead of PDF's built-in fonts.```

I'm pretty sure it's because I pull their username from twitter (as their "name"), and their username has random characters used for stylistic purposes.

Is there a good way to override this behavior somehow?

Thanks
- Pete

**Comment by pbmarcano** [comment]
Sorry, I don't think this was the right place for this issue.

**Comment by adrianthedev** [comment]
Check out this answer (https://github.com/excid3/receipts/issues/28#issuecomment-3196085867)
