### ISSUE TITLE
Logo showing extremely small on invoice

### ISSUE THREAD

**Issue by basharabdullah** [excid3/receipts#23]
Using latest Receipts gem version ```2.1.0```, and for some reason the logo always appears too small, unlike the one shown at Readme. I tried to trace the code, and if I understand correctly, the height is set to 16 by default? Sorry if I'm mistaken. 

How can I specify a larger logo size?

**Comment by excid3** [comment]
Seems like a good config option we could add.

**Comment by basharabdullah** [comment]
Would definitely be helpful. But even without it, should the logo be this small? I'm trying logos of different and large sizes, but get something like this.

<img width="776" alt="Screen Shot 2022-12-07 at 8 02 27 AM" src="https://user-images.githubusercontent.com/167290/206093051-7ed3d9e4-2ac8-4d6c-98f8-54e0ae626e0a.png">

**Comment by excid3** [comment]
Yes, it's designed for a logo with the mark and word as you can see in the [examples](https://github.com/excid3/receipts/blob/master/examples/).

https://github.com/excid3/receipts/blob/master/examples/invoice.pdf

**Comment by basharabdullah** [comment]
I see. That makes sense. Thought text was part of the logo. My bad. Thanks
:)
