### ISSUE TITLE
make page_size configurable

### ISSUE THREAD

**Issue by whysthatso** [excid3/receipts#25]
Thanks for this gem of a gem, it makes using prawn so much more reasonable.

is there a way to add page_size as a configurable?

as it is in the `initialize` function, i'm not sure how to override or configure it best. if you could give me some hints, i might be able to come up with a pr.

**Comment by excid3** [comment]
We probably need to change this
```ruby
    def initialize(attributes = {})
      super(page_size: "LETTER")
```

To:
```ruby
super(page_size: attributes.delete(:page_size) || "LETTER")
```

**Comment by whysthatso** [comment]
haha, you're too reactive. i had hoped to twiddle together a nice naive pr :D
thanks.

**Comment by excid3** [comment]
It turns out that I already had this code on my laptop sitting in git staging from like a month ago and I just had to commit it. 😅

**Comment by excid3** [comment]
I'm sure there are lots of other improvements to be done, so PRs are welcome!
