### ISSUE TITLE
Matrix gem dependency requires users to add matrix gem in Gemfile when using receipts.

### ISSUE THREAD

**Issue by schadenfred** [excid3/receipts#27]
Looks like this gem depends on prawn which depends on matrix, which was removed from the standard library in 3.1, and caused an error for me on deploy. The error went away once I declared the matrix gem explicitly in my Gemfile. I believe this may be fixed upstream by prawn at some point but in the interim, it may prove beneficial to add matrix as a dependency in the gemspec for this gem. Let me know if you'd like a pr.

**Comment by excid3** [comment]
You should update Rubygems. `gem update --system`

**Comment by excid3** [comment]
We're still waiting on a new prawn release, so we recommend using it directly from github. We might want to update our readme to mention that for now. 

I don't know if they will ever make a new release and we may also switch to another PDF backend. 🙃

**Comment by excid3** [comment]
I think this is good now. I believe you want to `gem update --system` to make sure you're on the latest Rubygems and Bundler.

Details on the matrix gem as a standard gem: https://stdgems.org/matrix/

**Comment by schadenfred** [comment]
Outstanding.
