### ISSUE TITLE
Getting Prawn::Errors::IncompatibleStringEncoding

### ISSUE THREAD

**Issue by dnara** [excid3/receipts#28]
It does not encode non-alphabet characters. 

```
Your document includes text that's not compatible with the Windows-1252 character set.
If you need full UTF-8 support, use external fonts instead of PDF's built-in fonts.
```
According to this (see: https://github.com/jessedoyle/prawn-icon/issues/44), the prawn-table needs to be pointed as below:

```
# in Gemfile
gem 'prawn-table', git: 'https://github.com/prawnpdf/prawn-table.git'  
``` 

The Gemfile in my app is already pointed as above, but it still does not work. 

Maybe you need to update your Gemfile?

**Comment by dnara** [comment]
I end up downloading ttf files and set them as defaults font in the initializer as described in the documentation. 
I removed prawn-table gem from my app and it works without it.

**Comment by adrianthedev** [comment]
For those looking for a quick fix:

- download the fonts from [here](https://font.download/font/helvetica-255)
- add this to your script

```ruby
  MY_FONTS = {
    "Helvetica": {
      normal: Rails.root.join("app/assets/fonts/Helvetica.ttf"),
      italic: Rails.root.join("app/assets/fonts/Helvetica-Oblique.ttf"),
      bold: Rails.root.join("app/assets/fonts/Helvetica-Bold.ttf"),
      bold_italic: Rails.root.join("app/assets/fonts/Helvetica-BoldOblique.ttf")
    }
  }

  Receipts.default_font = MY_FONTS[:Helvetica] # this to set the fonts
  
  @invoice = Receipts::Invoice.new(
    ...
```

**Comment by adrianthedev** [comment]
Just a friendly PSA: If you're trying to mail that invoice it will be quite huge and will probably fail to be sent.

I started to do something else


```ruby
  def transliterate(text)
    ActiveSupport::Inflector.transliterate(text).encode("Windows-1252")
  end

  # and use it like so 
  transliterate("Gwiaździsta") # Gwiazdzista
```
