### ISSUE TITLE
Document title not translatable

### ISSUE THREAD

**Issue by uurcank** [excid3/receipts#29]
The document titles "Receipt", "Invoice", "Statement" [are inherited from the class name](https://github.com/excid3/receipts/blob/f6f7f85192f1e569ca7c003d64829e2f50388eec/lib/receipts/base.rb#L13C47-L13C47), which makes them non-translatable. 

Even if you start empty, there is not an option to set a custom title. Am I missing anything?

 It may be better to remove this dependency and just use the class name as fallback when no title option present.

**Comment by uurcank** [comment]
it is already a fallback to the title attribute but not documented so this works

```
Receipts::Receipt.new(
   title: "Package slip",
    )
    
```

**Comment by excid3** [comment]
Wanna make a PR to add that to the docs?
