### ISSUE TITLE
How to horizontally centered the line_items?

### ISSUE THREAD

**Issue by zulhfreelancer** [excid3/receipts#5]
Hi,

Is it possible for me to place the `line_items` at center of the generated PDF (horizontally) instead of flush left?

How to do it?

Do I need to play with CSS?

Thanks.

**Comment by excid3** [comment]
This is built on Prawn so you'll want to look into Prawn's alignment options. I think you can center tables and/or the contents pretty easily. You'd just create a new class, inherit from the Receipt one in this gem, and override any of the methods for generating the PDF that you want to customize.

**Comment by zulhfreelancer** [comment]
Noted. Thanks!
