### ISSUE TITLE
How to customise RECEIPT FOR CHARGE line 

### ISSUE THREAD

**Issue by nirbelelti** [excid3/receipts#9]
Hi,

Thank you for really nice gem, I'm using it  and I really like it. 

How can I customise the message on the header RECEIPT FOR CHARGE # ? 
I'm creating receipts in foreign language and would like to customise this message

Thank you

**Comment by excid3** [comment]
I just released 0.2.2 with a way to customize that subheading. Pass in the subheading option like `subheading: "RECEIPT FOR CHARGE #%{id}"` to customize it. `%{id}` will be replaced with the ID.
